// Autogenerated from Pigeon (v20.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class ACMemoryUsage;
@class ACStartupTime;

@interface ACMemoryUsage : NSObject
+ (instancetype)makeWithDirtyMemoryUsage:(nullable NSNumber *)dirtyMemoryUsage
    ownedSharedMemoryUsage:(nullable NSNumber *)ownedSharedMemoryUsage;
@property(nonatomic, strong, nullable) NSNumber * dirtyMemoryUsage;
@property(nonatomic, strong, nullable) NSNumber * ownedSharedMemoryUsage;
@end

@interface ACStartupTime : NSObject
+ (instancetype)makeWithStartupTime:(nullable NSNumber *)startupTime;
@property(nonatomic, strong, nullable) NSNumber * startupTime;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *ACGetMessagesCodec(void);

@protocol ACPollIosStats
/// @return `nil` only when `error != nil`.
- (nullable ACMemoryUsage *)pollMemoryUsageWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable ACStartupTime *)pollStartupTimeWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpACPollIosStats(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ACPollIosStats> *_Nullable api);

extern void SetUpACPollIosStatsWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ACPollIosStats> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
